### ISSUE TITLE
Not integrating with nautilus.

### ISSUE THREAD

**Issue by rohitghali** [Diaoul/nautilus-subliminal#19]
wget didn't work. So I manually downloaded the file and installed it. It installed good. Screenshot also attached. I even restarted the system. Still nothing in the right click options. Please help.

![screenshot from 2018-09-18 18-40-20](https://user-images.githubusercontent.com/42379398/45689790-734ea580-bb72-11e8-91df-9ac34dc309c3.png)

**Comment by yuzvir** [comment]
run nautilus from terminal and you will probably see error log
for example, mine looked like this:
```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-subliminal.py", line 137, in __init__
    os.makedirs(dirs.user_cache_dir)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/user/.cache/subliminal'
```
so, I opened nautilus-subliminal.py and changed these lines (line 137-138)
```
                os.makedirs(dirs.user_cache_dir)
                os.makedirs(dirs.user_config_dir)
```
to these
```
            if not os.path.exists(dirs.user_cache_dir):
                os.makedirs(dirs.user_cache_dir)
            if not os.path.exists(dirs.user_cache_dir):
                os.makedirs(dirs.user_config_dir)
```
and now it works

**Comment by yosko** [comment]
Worked for me. Thanks @yuzvir .
It might be a good idea to turn this into a pull request.
