### ISSUE TITLE
Python error when attempting to select or download subtites

### ISSUE THREAD

**Issue by guillomovitch** [Diaoul/nautilus-subliminal#28]
When attempting  to select or download subtites for any video file:
```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-subliminal.py", line 186, in choose_callback
    refine(video, episode_refiners=self.config.refiners, movie_refiners=self.config.refiners,
  File "/usr/lib/python3.8/site-packages/subliminal/core.py", line 546, in refine
    for refiner in ('hash', ) + refiners:
TypeError: can only concatenate tuple (not "list") to tuple
```

The actual issue could be in subliminal, rather than in nautilus-subliminal, tough.

I'm using python 3.8, subliminal 2.1.0, and nautilus 3.36, on mageia cauldron.

**Comment by todoneunl** [comment]
Same for me. Is this repo still maintained?
